import random
import os


path = "D:\icecreamImg"

file_list = os.listdir(path)
print("file_list: {}".format(file_list))
test2 = [
    "거북알.jpg",
    "거북이.jpg",
    "고드름.jpg",
    "구구바.jpg",
    "구구콘.jpg",
    "구구크러스터.jpg",
    "국화빵.jpg",
    "그릭요거트바.jpg",
    "까페오레.jpg",
    "끌레도르.jpg",
    "나뚜루.jpg",
    "녹차마루.jpg",
    "누가바.jpg",
    "대롱대롱.jpg",
    "더블비얀코.png",
    "더위사냥.jpg",
    "델몬트망고.jpg",
    "돼지바.jpg",
    "돼지콘.jpg",
    "디핀다트.png",
    "리틀텐.jpg",
    "메가톤바.jpg",
    "메로나.jpg",
    "모히또바.jpg",
    "미니멜츠.jpg",
    "민트초콜릿칩.png",
    "밀키스바.jpg",
    "바람과함께사라지다.png",
    "바밤바.jpg",
    "배스킨라비스컵.png",
    "베리베리스트로베리.png",
    "별난바.jpg",
    "보석바.jpg",
    "부라보콘.jpg",
    "붕어싸만코.jpg",
    "블루소다.jpg",
    "비비빅.jpg",
    "빙빙바.jpg",
    "빠삐코바.jpg",
    "빵또아.png",
    "빵빠레.jpg",
    "뽕따.png",
    "사랑에빠진딸기.png",
    "생귤탱귤.png",
    "설레임.jpg",
    "수박맛바.jpg",
    "순수밀크.jpg",
    "슈팅스타.png",
    "슈퍼콘.jpg",
    "스크류바.png",
    "쌍쌍바.jpg",
    "아맛나.jpg",
    "아몬드봉봉.png",
    "아차차.jpg",
    "아포가토.png",
    "알껌바.jpg",
    "알초코바.jpg",
    "엄마는 외계인.png",
    "엔초.jpg",
    "옥동자.jpg",
    "와삭바.jpg",
    "와일드바디.jpg",
    "요맘때.jpg",
    "월드콘.jpg",
    "위즐.jpg",
    "이상한나라의솜사탕.png",
    "젤루조아.jpg",
    "조안나.jpg",
    "죠스바.jpg",
    "주물러.jpg",
    "찰떡시모나.jpg",
    "찰떡아이스.jpg",
    "찰옥수수.jpg",
    "체리마루.jpg",
    "체리쥬빌레.png",
    "초코나무숲.png",
    "초코퍼지.jpg",
    "캔디바.jpg",
    "쿠앤크.jpg",
    "쿠키오.jpg",
    "키위아작.png",
    "탱크보이.jpg",
    "테트리스.jpg",
    "토마토마.jpg",
    "투게더.png",
    "티라미수.jpg",
    "판타스틱트롤.png",
    "팥빙수.jpg",
    "팽이팽이.jpg",
    "폭신폭신솜사탕바.jpg",
    "폴라포.jpg",
    "호두마루.jpg",
]
"""
test = {
    "list": [
        {"id": "0", "name": "거북알", "img": "img1"},
        {"id": "1", "name": "거북이", "img": "img2"},
        {"id": "2", "name": "고드름", "img": "img3"},
        {"id": "3", "name": "구구바", "img": "img4"},
        {"id": "4", "name": "구구콘", "img": "img5"},
    ]
}

mlist = test.get("list")
random.shuffle(mlist)

test["list"] = mlist
print(test)
"""
