import random

test = {
    "list": [
        {"id": "0", "name": "거북알", "img": "img0"},
        {"id": "1", "name": "거북이", "img": "img1"},
        {"id": "2", "name": "고드름", "img": "img2"},
        {"id": "3", "name": "구구바", "img": "img3"},
        {"id": "4", "name": "구구콘", "img": "img4"},
        {"id": "5", "name": "구구크러스터", "img": "img5"},
        {"id": "6", "name": "국화빵", "img": "img6"},
        {"id": "7", "name": "그릭요거트바", "img": "img7"},
        {"id": "8", "name": "까페오레", "img": "img8"},
        {"id": "9", "name": "끌레도르", "img": "img9"},
        {"id": "10", "name": "나뚜루", "img": "img10"},
        {"id": "11", "name": "녹차마루", "img": "img11"},
        {"id": "12", "name": "누가바", "img": "img12"},
        {"id": "13", "name": "대롱대롱", "img": "img13"},
        {"id": "14", "name": "더블비얀코", "img": "img14"},
        {"id": "15", "name": "더위사냥", "img": "img15"},
        {"id": "16", "name": "델몬트망고", "img": "img16"},
        {"id": "17", "name": "돼지바", "img": "img17"},
        {"id": "18", "name": "돼지콘", "img": "img18"},
        {"id": "19", "name": "디핀다트", "img": "img19"},
        {"id": "20", "name": "리틀텐", "img": "img20"},
        {"id": "21", "name": "메가톤바", "img": "img21"},
        {"id": "22", "name": "메로나", "img": "img22"},
        {"id": "23", "name": "모히또바", "img": "img23"},
        {"id": "24", "name": "미니멜츠", "img": "img24"},
        {"id": "25", "name": "민트초콜릿칩", "img": "img25"},
        {"id": "26", "name": "밀키스바", "img": "img26"},
        {"id": "27", "name": "바람과함께사라지다", "img": "img27"},
        {"id": "28", "name": "바밤바", "img": "img28"},
        {"id": "29", "name": "베리베리스트로베리", "img": "img29"},
        {"id": "30", "name": "별난바", "img": "img30"},
        {"id": "31", "name": "보석바", "img": "img31"},
        {"id": "32", "name": "부라보콘", "img": "img32"},
        {"id": "33", "name": "붕어싸만코", "img": "img33"},
        {"id": "34", "name": "블루소다", "img": "img34"},
        {"id": "35", "name": "비비빅", "img": "img35"},
        {"id": "36", "name": "빙빙바", "img": "img36"},
        {"id": "37", "name": "빠삐코바", "img": "img37"},
        {"id": "38", "name": "빵또아", "img": "img38"},
        {"id": "39", "name": "빵빠레", "img": "img39"},
        {"id": "40", "name": "뽕따", "img": "img40"},
        {"id": "41", "name": "사랑에빠진딸기", "img": "img41"},
        {"id": "42", "name": "생귤탱귤", "img": "img42"},
        {"id": "43", "name": "설레임", "img": "img43"},
        {"id": "44", "name": "수박맛바", "img": "img44"},
        {"id": "45", "name": "순수밀크", "img": "img45"},
        {"id": "46", "name": "슈팅스타", "img": "img46"},
        {"id": "47", "name": "슈퍼콘", "img": "img47"},
        {"id": "48", "name": "스크류바", "img": "img48"},
        {"id": "49", "name": "쌍쌍바", "img": "img49"},
        {"id": "50", "name": "아맛나", "img": "img50"},
        {"id": "51", "name": "아몬드봉봉", "img": "img51"},
        {"id": "52", "name": "아차차", "img": "img52"},
        {"id": "53", "name": "아포가토", "img": "img53"},
        {"id": "54", "name": "알껌바", "img": "img54"},
        {"id": "55", "name": "알초코바", "img": "img55"},
        {"id": "56", "name": "엄마는외계인", "img": "img56"},
        {"id": "57", "name": "엔초", "img": "img57"},
        {"id": "58", "name": "옥동자", "img": "img58"},
        {"id": "59", "name": "와삭바", "img": "img59"},
        {"id": "60", "name": "와일드바디", "img": "img60"},
        {"id": "61", "name": "요맘때", "img": "img61"},
        {"id": "62", "name": "월드콘", "img": "img62"},
        {"id": "63", "name": "위즐", "img": "img63"},
        {"id": "64", "name": "이상한나라의솜사탕", "img": "img64"},
        {"id": "65", "name": "젤루조아", "img": "img65"},
        {"id": "66", "name": "조안나", "img": "img66"},
        {"id": "67", "name": "죠스바", "img": "img67"},
        {"id": "68", "name": "주물러", "img": "img68"},
        {"id": "69", "name": "시모나", "img": "img69"},
        {"id": "70", "name": "찰떡아이스", "img": "img70"},
        {"id": "71", "name": "찰옥수수", "img": "img71"},
        {"id": "72", "name": "체리마루", "img": "img72"},
        {"id": "73", "name": "체리쥬빌레", "img": "img73"},
        {"id": "74", "name": "초코나무숲", "img": "img74"},
        {"id": "75", "name": "초코퍼지", "img": "img75"},
        {"id": "76", "name": "캔디바", "img": "img76"},
        {"id": "77", "name": "쿠앤크", "img": "img77"},
        {"id": "78", "name": "쿠키오", "img": "img78"},
        {"id": "79", "name": "키위아작", "img": "img79"},
        {"id": "80", "name": "탱크보이", "img": "img80"},
        {"id": "81", "name": "테트리스", "img": "img81"},
        {"id": "82", "name": "토마토마", "img": "img82"},
        {"id": "83", "name": "투게더", "img": "img83"},
        {"id": "84", "name": "티라미수", "img": "img84"},
        {"id": "85", "name": "판타스틱트롤", "img": "img85"},
        {"id": "86", "name": "팥빙수", "img": "img86"},
        {"id": "87", "name": "팽이팽이", "img": "img87"},
        {"id": "88", "name": "폭신폭신솜사탕바", "img": "img88"},
        {"id": "89", "name": "폴라포", "img": "img89"},
        {"id": "90", "name": "호두마루", "img": "img90"},
    ]
}

mlist = test.get("list")
random.shuffle(mlist)

test["list"] = mlist
print(test)
